# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 3.93.184.113:8083/springapp
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 97
  imagePullSecrets:
  - name: registry-secret
imageCredentials:
  name: docker-hosted_credentials
  registry: 3.93.184.113:8083
  username: admin
  password: lex@luthor13

service:
  type: NodePort
  port: 8080

